### ISSUE TITLE
Some possible bugs

### ISSUE THREAD

**Issue by evanrutledge1** [EymenWinnerYT/PHP-MDParser#1]
Hello. I think I've found a bug. If you type "#" on accident in any string, it could read it. So if you said "User #3 said such and such", "3" would be read as a header.

**Comment by evanrutledge1** [comment]
> yeah don't use general paragraphs in $psr->parse() method. Use this for text which you want to apply markdown to it.

What if I added this to a social-based site (Eg Gr8brik)? How could I filter what content in the posts?

**Comment by EymenWinnerYT** [comment]
switch bbcode with my markdown interpeter

**Comment by evanrutledge1** [comment]
> switch bbcode with my markdown interpeter

I'll think about it.
